config/routes.rb
Passport::Application.routes.draw do

  scope :auth do
    devise_for :users
  end

  scope :api, defaults: { format: :json } do
    get 'validate_key' => 'api#validate_key'
    get 'users/current_user' => 'users#active_user'
    resources :users, as: 'api_users'
    resources :apps, as: 'api_apps'
  end

  resources :users
  resources :apps

  get 'apps/access/:id' => 'apps#access'
  get 'apps/dashboard' => 'apps#dashboard'
  root 'apps#dashboard'

  

end

app/models/access_key.rb
class AccessKey < ActiveRecord::Base
	belongs_to :user
	
	def self.gen(user)
		key = SecureRandom.hex
		access_key = self.create(
			key: key,
			expire_at: DateTime.now + 30.minutes,
			user: user
		)
		key
	end

	def renew
		self.expire_at = DateTime.now + 30.minutes
		self.save
	end

	def is_valid
		self.expire_at >= DateTime.now
	end
end

app/models/app.rb
class App < ActiveRecord::Base
	has_many :user_apps
	ACTIVE = 1
	
	def uri
		url
	end

	def uri=(uri)
		url = uri
	end

	def all_active
		
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  def has_access_to(app)
  	UserApp.exists?(app: app, user: self)
  end
end

app/models/user_app.rb
class UserApp < ActiveRecord::Base
  belongs_to :user
  belongs_to :app
end

app/controllers/api_controller.rb
# encoding: utf-8

class ApiController < ApplicationController
  def validate_key
    render :nothing=>true
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_filter :authenticate_user!, :unless => ->(controller){ controller.request.format.json? }
  before_filter :restrict_api_access, :if => ->(controller){ controller.request.format.json? }
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  #protect_from_forgery with: :exception

  private

		def restrict_api_access
			access_key = AccessKey.find_by_key(params[:k])
			if access_key and access_key.is_valid
				access_key.renew
				if !user_signed_in?
					sign_in access_key.user
				end
			else
		 		head :unauthorized
		  end
		end
end

app/controllers/apps_controller.rb
class AppsController < ApplicationController
  before_action :set_app, only: [:show, :edit, :update, :destroy, :access]

  def dashboard
    @apps = App.all
  end

  # GET /apps
  # GET /apps.json
  def index
    @apps = App.joins(:user_apps).where('user_apps.app_id = apps.id AND user_apps.user_id = ?', current_user.id)
  end

  def access
    uri =  URI.parse(@app.uri)
    new_query_ar = URI.decode_www_form(uri.query) << ["k", AccessKey.gen(current_user)]
    uri.query = URI.encode_www_form(new_query_ar)
    puts uri.to_s, @app.uri
    redirect_to uri.to_s
  end

  # GET /apps/1
  # GET /apps/1.json
  def show
  end

  # GET /apps/new
  def new
    @app = App.new
  end

  # GET /apps/1/edit
  def edit
  end

  # POST /apps
  # POST /apps.json
  def create
    @app = App.new(app_params)

    respond_to do |format|
      if @app.save
        format.html { redirect_to apps_path, notice: 'App foi criado com sucesso.' }
        format.json { render action: 'show', status: :created, location: @app }
      else
        format.html { render action: 'new' }
        format.json { render json: @app.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /apps/1
  # PATCH/PUT /apps/1.json
  def update
    respond_to do |format|
      if @app.update(app_params)
        format.html { redirect_to apps_path, notice: 'App foi atualizado com sucesso.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @app.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /apps/1
  # DELETE /apps/1.json
  def destroy
    @app.destroy
    respond_to do |format|
      format.html { redirect_to apps_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_app
      @app = App.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def app_params
      params.require(:app).permit(:name, :status, :url, :icon)
    end
end

app/controllers/users_controller.rb
# encoding: utf-8

class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :set_apps_options, only: [:edit, :new, :update, :create]

  def active_user
    access_key = AccessKey.find_by_key(params[:k])
    respond_to do |format|
      format.json {render json: access_key.user}
    end
  end

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        params[:apps_prompted].each do |app_id|
          UserApp.where(user: @user, app_id: app_id).destroy_all
        end
        params[:apps_confirmed].each do |app_id|
          UserApp.create(user: @user, app_id: app_id)
        end
        format.html { redirect_to users_path, notice: 'Usuário criado com sucesso.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        params[:apps_prompted].each do |app_id|
          UserApp.where(user: @user, app_id: app_id).destroy_all
        end
        params[:apps_confirmed].each do |app_id|
          UserApp.create(user: @user, app_id: app_id)
        end
        format.html { redirect_to users_path, notice: 'Usuário atualizado com sucesso.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    def set_apps_options
      #not implemented
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      if params[:user][:password].blank?
        params[:user].delete(:password)
        params[:user].delete(:password_confirmation)
      end
      params[:apps_confirmed] = params[:apps_confirmed] || []
      params[:apps_prompted] = params[:apps_prompted] || []
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/apps_helper.rb
module AppsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/apps/_form.html.erb
<%= form_for(@app) do |f| %>
  <% if @app.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@app.errors.count, "error") %> prohibited this app from being saved:</h2>

      <ul>
      <% @app.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, :class=>'form-control' %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url, :class=>'form-control' %>
  </div>
  <div class="field">
    <%= f.label :icon %><br>
    <%= f.text_area :icon, :class=>'form-control' %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit 'Salvar', :class=>'btn btn-primary' %>
  </div>
<% end %>

app/views/apps/dashboard.html.erb
<div class="relative">
  <h1>Aplicativos disponíveis</h1>
</div>
<% if notice %>
<p class="alert alert-success alert-dismissable"><%= notice %></p>
<% end %>
<ul class="list-apps">
<% @apps.each do |app| %>
  <%= link_to({:action=>'access', :id=>app.id}, target: '_blank') do %>
    <%= app.icon.html_safe %>
    <div class="app-name"><%= app.name %></div>
  <% end %>
<% end %>
</ul>
      
<div class="row">
  <div class="col-md-6">
      <!-- Agenda -->
  </div>
  <div class="col-md-6">
      <!-- Tab -->
  </div>
</div>

app/views/apps/edit.html.erb
<div class="relative">
  <h1>Editar app</h1>
  <div class="sidebar-menu">
      <ul>
          <li>
            <%= link_to '<i class="fa fa-arrow-left"></i>Voltar'.html_safe, apps_path %>
          </li>
      </ul>
  </div>
</div>

<%= render 'form' %>

app/views/apps/index.html.erb
<div class="relative">
  <h1>Aplicativos</h1>
  <div class="sidebar-menu">
      <ul>
          <li>
            <%= link_to '<i class="fa fa-plus"></i>Inserir'.html_safe, new_app_path %>
          </li>
      </ul>
  </div>
</div>
<% if notice %>
<p class="alert alert-success alert-dismissable"><%= notice %></p>
<% end %>
<table class="table table-hover">
<% @apps.each do |app| %>
  <tr>
    <td>
      <%= link_to action: 'access', id: app.id do %>
        <%= app.name %>
      <% end %>
    </td>
    <td>
      <%= app.uri %>
    </td>
    <td>
      <%= link_to '<i class="fa fa-pencil"></i>'.html_safe, edit_app_path(app) %>
      <%= link_to '<i class="fa fa-trash-o"></i>'.html_safe, app, method: :delete, data: { confirm: 'Are you sure?' } %>
    </td>
  <% end %>
  </tr>
</table>

app/views/apps/new.html.erb
<div class="relative">
  <h1>Novo app</h1>
  <div class="sidebar-menu">
      <ul>
          <li>
            <%= link_to '<i class="fa fa-arrow-left"></i>Voltar'.html_safe, apps_path %>
          </li>
      </ul>
  </div>
</div>

<%= render 'form' %>

app/views/apps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @app.name %>
</p>

<p>
  <strong>Status:</strong>
  <%= @app.status %>
</p>

<p>
  <strong>Url:</strong>
  <%= @app.url %>
</p>

<p>
  <strong>Icon:</strong>
  <%= @app.icon %>
</p>

<%= link_to 'Edit', edit_app_path(@app) %> |
<%= link_to 'Back', apps_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Acess@</title>
	  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	  <%= csrf_meta_tags %>
	</head>
	<body id="app">
	 <header>
	    <div class="row">
        <div class="col-sm-6">
           <div class="brand"><a href="/"><%= image_tag "logo.png" %></a></div>
        </div>
        <div class="col-sm-6">
        <% if user_signed_in? %>
          <div class="pull-right panel-user">
            <span><%= current_user.email %></span>
            <%= link_to apps_path, :style=>'vertical-align: text-top;' do -%>
	            <i class="fa fa-th"></i>
	          <% end -%>
            <%= link_to users_path do -%>
	            <i class="fa fa-users"></i>
	          <% end -%>
            <%= link_to destroy_user_session_path, :method => :delete do -%>
	            <i class="fa fa-power-off"></i>
	          <% end -%>
          </div>
        <% end %>
        </div>
	    </div>
		</header>
		<section>
			<%= yield %>
		</section>
		<footer>
		  <div class="footer-gv">
	      <p>FGVces - www.fgv.br/ces | Avenida 9 de Julho, 2029 - 11º andar - São Paulo/SP | (11) 3799-3342<br>
	      © 2014. Todos os direitos reservados.</p>
		  </div>
		</footer>
	</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email, :class=>'form-control' %>
  </div>

  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password, :class=>'form-control' %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation, :class=>'form-control' %>
  </div>
  <h2>Aplicativos disponíveis</h2>
  <ul style="list-style: none; margin: 20px -20px;">
    <% App.all.each do |app| %>
      <li>
        <%= hidden_field_tag "apps_prompted[]", app.id %>
        <%= check_box_tag "apps_confirmed[]", app.id, @user.has_access_to(app) %>
        <%= label_tag app.name, nil, :style=>'vertical-align: top;' %>
      </li>
    <% end %>
  </ul>

  <div class="actions">
    <%= f.submit 'Salvar', :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="relative">
  <h1>Editar usuário</h1>
  <div class="sidebar-menu">
      <ul>
          <li>
            <%= link_to '<i class="fa fa-arrow-left"></i>Voltar'.html_safe, users_path %>
          </li>
      </ul>
  </div>
</div>

<%= render 'form' %>

app/views/users/index.html.erb
<div class="relative">
  <h1>Usuários</h1>
  <div class="sidebar-menu">
      <ul>
          <li>
            <%= link_to '<i class="fa fa-plus"></i>Inserir'.html_safe, new_user_path %>
          </li>
          <li>
            <%= link_to '<i class="fa fa-arrow-left"></i>Voltar'.html_safe, apps_path %>
          </li>
      </ul>
  </div>
</div>
<% if notice %>
<p class="alert alert-success alert-dismissable"><%= notice %></p>
<% end %>
<table class="table table-hover">
<% @users.each do |user| %>
  <tr>
    <td><%= user.email %></td>
    <td>
    <%= link_to '<i class="fa fa-pencil"></i>'.html_safe, edit_user_path(user) %>
    <%= link_to '<i class="fa fa-trash-o"></i>'.html_safe, user, method: :delete, data: { confirm: 'Are you sure?' } %>
    </td>
  </tr>
<% end %>
</table>

app/views/users/new.html.erb
<div class="relative">
  <h1>Novo usuário</h1>
  <div class="sidebar-menu">
      <ul>
          <li>
            <%= link_to '<i class="fa fa-arrow-left"></i>Voltar'.html_safe, users_path %>
          </li>
      </ul>
  </div>
</div>

<%= render 'form' %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>